# Generated by Django 4.1.4 on 2023-06-02 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_filemessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created Timestamp')),
                ('status', models.IntegerField(choices=[(1, 'Created'), (2, 'Blocked'), (3, 'Merged')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='CategorySubcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=512)),
                ('subcategory', models.CharField(max_length=512)),
                ('language', models.CharField(choices=[('english', 'en'), ('hindi', 'hi'), ('gujarati', 'gj'), ('marathi', 'mr')], default='english', max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('location', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('client_number', models.CharField(max_length=16, unique=True)),
                ('lastSMSSent', models.DateTimeField(auto_now=True, null=True, verbose_name='Last SMS Timestamp')),
                ('status', models.IntegerField(choices=[(1, 'Active'), (2, 'Blocked')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='HelperCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='HelpLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='General', max_length=64)),
                ('helpline_number', models.CharField(max_length=16, unique=True)),
                ('helpline_tollfree_number', models.CharField(default=None, max_length=16, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=20)),
                ('helpline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.helpline')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created Timestamp')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified Timestamp')),
                ('tag_string', models.CharField(blank=True, default='', max_length=256, null=True)),
                ('task_type', models.IntegerField(choices=[(1, 'DIRECT'), (2, 'INDIRECT')], default=2)),
                ('status', models.IntegerField(choices=[(1, 'Pending'), (2, 'Completed'), (3, 'Rejected')], default=1)),
                ('call_attempt', models.IntegerField(default=0)),
                ('client_calls', models.IntegerField(default=1)),
                ('from_whatsapp', models.BooleanField(blank=True, default=False)),
                ('call_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='chat.callrequest')),
                ('category', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='chat.helpercategory')),
                ('language', models.ManyToManyField(blank=True, to='chat.language')),
                ('taskcategory', models.ManyToManyField(blank=True, default=None, related_name='taskcategory', to='chat.categorysubcategory')),
                ('tasksubcategory', models.ManyToManyField(blank=True, default=None, related_name='tasksubcategory', to='chat.categorysubcategory')),
            ],
        ),
        migrations.AddField(
            model_name='helpercategory',
            name='helpline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.helpline'),
        ),
        migrations.AddField(
            model_name='categorysubcategory',
            name='helpline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.helpline'),
        ),
        migrations.AddField(
            model_name='callrequest',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_requests', to='chat.client'),
        ),
        migrations.AddField(
            model_name='callrequest',
            name='helpline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_requests', to='chat.helpline'),
        ),
    ]
