# Generated by Django 4.1.4 on 2023-06-08 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_callrequest_categorysubcategory_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='file',
            field=models.FileField(blank=True, upload_to='chat'),
        ),
        migrations.AddField(
            model_name='message',
            name='filename',
            field=models.FileField(blank=True, upload_to='chat'),
        ),
    ]
