# Generated by Django 4.1.4 on 2023-06-08 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_message_file_message_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='filename',
            field=models.TextField(blank=True),
        ),
    ]
