# Generated by Django 4.1.4 on 2023-06-21 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_files_delete_filemessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
